### ISSUE TITLE
Linker

### ISSUE THREAD

**Issue by alejandro-colomar** [ivanp7/still-alive#1]
As I said in fake-bsod, it doesn't compile on Debian.

If you have it, I recommend you to use `pkg-config --libs ncursesw` (substituting -l:libncursesw.a), that would be more portable.

If you don't have it, install it :)

**Comment by ivanp7** [comment]
Thank you! You have just improved my skills :)

**Comment by alejandro-colomar** [comment]
You're welcome!  :)
